version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.48.0-rc.0 # Use a specific version instead of latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 8198:9090

  grafana:
    image: grafana/grafana:10.1.5 # Use a specific version instead of latest
    container_name: grafana
    ports:
      - 8197:3000
    volumes:
      - ./grafana/data:/var/lib/grafana # If you want to persist Grafana data
